name: CI-CD Pipeline
on:
  push:
    branches: [ dev, main ]
jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
      - name: Install Azure CLI and Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y curl zip docker.io
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          sudo systemctl start docker
          sudo usermod -aG docker $USER
      - name: Build and Push Docker Image
        run: |
          cd MeuProjeto
          docker build -t lucasmgpy/legacylmg-app:latest .
          docker push lucasmgpy/legacylmg-app:latest
      - name: Deploy to Azure
        if: github.ref == 'refs/heads/main'
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az webapp config container set --name legacylmg-app --resource-group legacylmg-rg --container-image-name lucasmgpy/legacylmg-app:latest --container-registry-url https://index.docker.io
          az webapp restart --name legacylmg-app --resource-group legacylmg-rg
