name: CI-CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl zip
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Deploy to Azure
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          echo "Current working directory: $PWD"
          cd MeuProjeto
          echo "Now in directory: $PWD"
          dotnet publish -c Release -o publish
          ls -la publish
          zip -r publish.zip publish
          ls -la
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az webapp deployment source config-zip --resource-group legacylmg-rg --name legacylmg-app --src publish.zip
